# docker-compose.yml
version: '3'
networks:
  todoapp-net:
services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234z
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
